import { useState, useEffect, useRef } from "react";
import SearchBar from "./components/SearchBar";
import DatasetToggle from "./components/DatasetToggle";
import AnswerPanel from "./components/AnswerPanel";
import CitationCard from "./components/CitationCard";
import { queryRAG, getSuggestions } from "./api/client";
import "./App.css";

const HINTS = [
  "Which nonprofits raised the most money?",
  "Which PACs spent the most in 2024?",
  "Find nonprofits with high officer compensation",
  "What did Harris for President report in 2024?",
  "Which organizations filed 990PF returns?",
];

const TEAM = [
  "Sai Manikanta Battula",
  "Bhavani Danthuri",
  "Ability Chikanya",
  "Hanok Naidu Suravarapu",
];

const LOADING_MESSAGES = [
  "Searching 1.2M+ organizations...",
  "Querying financial database...",
  "Retrieving relevant documents...",
  "Generating cited answer...",
];

export default function App() {
  const [question, setQuestion] = useState("");
  const [dataset, setDataset] = useState("both");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingMsg, setLoadingMsg] = useState(0);
  const [error, setError] = useState(null);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const [history, setHistory] = useState([]);
  const [responseTime, setResponseTime] = useState(null);
  const [suggestions, setSuggestions] = useState([]);
  const loadingInterval = useRef(null);
  const resultsRef = useRef(null);

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", darkMode ? "dark" : "light");
  }, [darkMode]);

  async function handleSearch(q) {
    const query = q || question;
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setSuggestions([]);
    setResponseTime(null);
    setLoadingMsg(0);

    // Rotate loading messages
    loadingInterval.current = setInterval(() => {
      setLoadingMsg((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 1200);

    setHistory((prev) => {
      const filtered = prev.filter((h) => h !== query);
      return [query, ...filtered].slice(0, 10);
    });

    const start = Date.now();
    try {
      const data = await queryRAG(query, dataset, 5);
      setResult(data);
      // Fetch chart data for analytics

      // Fetch related questions
      try {
        const sugg = await getSuggestions(query, dataset);
        console.log("Suggestions:", sugg);
        setSuggestions(sugg.suggestions || []);
      } catch (e) {
        setSuggestions([]);
      }
      setResponseTime(((Date.now() - start) / 1000).toFixed(1));
      setTimeout(() => {
        resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 100);
    } catch (err) {
      setError("Could not reach the API. Make sure the backend is running on port 8000.");
    } finally {
      setLoading(false);
      clearInterval(loadingInterval.current);
    }
  }

  function handleHistoryClick(q) {
    setQuestion(q);
    setSettingsOpen(false);
    handleSearch(q);
  }

  function handleExportPDF() {
    if (!result) return;
    const content = `
INVESTIGATIVE RAG — ANSWER REPORT

Question: ${result.question || question}

ANSWER:
${result.answer}

SOURCE DOCUMENTS (${result.citations?.length || 0}):
${result.citations?.map((c, i) => `[${i+1}] ${c.org_name || c.file_name} | ${c.source} | EIN: ${c.ein || 'N/A'}`).join('\n') || 'None'}

Generated by Investigative RAG System — Capstone Group 2
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `investigative-rag-answer-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="header-inner">
          <div className="header-left">
            <div className="logo-row">
              <div className="logo-icon">IR</div>
              <div className="logo-mark">Investigative <span>RAG</span></div>
            </div>
            <p className="header-sub">IRS 990 &amp; FEC Filing Intelligence System</p>
          </div>
          <button className="settings-btn" onClick={() => setSettingsOpen(true)}>
            ⚙ Settings
          </button>
        </div>
      </header>

      {/* Settings Panel */}
      {settingsOpen && (
        <>
          <div className="settings-overlay" onClick={() => setSettingsOpen(false)} />
          <div className="settings-panel">
            <div className="settings-header">
              <span className="settings-title">Settings</span>
              <button className="settings-close" onClick={() => setSettingsOpen(false)}>✕</button>
            </div>
            <div className="settings-body">
              <div className="settings-section-title">Appearance</div>
              <div className="theme-toggle">
                <div className="theme-toggle-label">
                  <span className="theme-icon">{darkMode ? "🌙" : "☀️"}</span>
                  {darkMode ? "Dark Mode" : "Light Mode"}
                </div>
                <label className="toggle-switch">
                  <input type="checkbox" checked={darkMode}
                    onChange={(e) => setDarkMode(e.target.checked)} />
                  <span className="toggle-slider" />
                </label>
              </div>

              <div className="settings-section-title">Search History</div>
              <div className="history-list">
                {history.length === 0 ? (
                  <p className="history-empty">No searches yet</p>
                ) : (
                  history.map((h, i) => (
                    <button key={i} className="history-item" onClick={() => handleHistoryClick(h)}>
                      {h}
                    </button>
                  ))
                )}
              </div>
              {history.length > 0 && (
                <button className="clear-history-btn" onClick={() => setHistory([])}>
                  Clear History
                </button>
              )}
            </div>
          </div>
        </>
      )}

      <main className="main">
        {/* Hero */}
        <div className="hero">
          <h1 className="hero-title">
            Follow the <span className="highlight">Money.</span>
          </h1>
          <p className="hero-desc">
            Ask investigative questions across 1.2M+ IRS nonprofit organizations
            and FEC political finance records. Get cited answers backed by real documents.
          </p>
        </div>

        {/* Search */}
        <section className="search-section">
          <DatasetToggle value={dataset} onChange={setDataset} />
          <SearchBar value={question} onChange={setQuestion}
            onSearch={handleSearch} loading={loading} />
          <div className="hints-row">
            <span className="hints-label">Try:</span>
            {HINTS.map((h) => (
              <button key={h} className="hint-btn"
                onClick={() => { setQuestion(h); handleSearch(h); }}>
                {h}
              </button>
            ))}
          </div>
        </section>

        {/* Stats */}
        <div className="stats-bar">
          <div className="stat-item">
            <span className="stat-value">1.2M+</span>
            <span className="stat-label">Organizations in Database</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">100K+</span>
            <span className="stat-label">Indexed Chunks</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">38K+</span>
            <span className="stat-label">FEC Committees</span>
          </div>
          <div className="stat-item">
            <span className="stat-value">2024–26</span>
            <span className="stat-label">Coverage Period</span>
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="error-banner">
            ⚠ {error}
            <div style={{fontSize:"0.75rem", marginTop:"4px", opacity:0.8}}>
              Make sure the backend is running: <code>uvicorn src.api.main:app --port 8000</code>
            </div>
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div className="loading-state">
            <div className="loading-dots">
              <span /><span /><span />
            </div>
            <p>{LOADING_MESSAGES[loadingMsg]}</p>
            <p style={{fontSize:"0.72rem", opacity:0.5, marginTop:"4px"}}>
              Searching {dataset === "irs" ? "IRS" : dataset === "fec" ? "FEC" : "IRS + FEC"} data sources
            </p>
          </div>
        )}

        {/* Results */}
        {suggestions.length > 0 && result && !loading && (
          <div className="suggestions-panel">
            <p className="suggestions-title">🔍 Related Questions</p>
            <div className="suggestions-list">
              {suggestions.map((s, i) => (
                <button
                  key={i}
                  className="suggestion-btn"
                  onClick={() => {
                    setQuestion(s);
                    handleSearch(s);
                  }}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}

        {result && !loading && (
          <section className="results-section" ref={resultsRef}>
            {/* Response meta bar */}
            <div className="response-meta">
              <span className="response-meta-item">
                ✓ Answer generated
              </span>
              {responseTime && (
                <span className="response-meta-item">
                  ⏱ {responseTime}s response time
                </span>
              )}
              {result.sources_used && (
                <span className="response-meta-item">
                  📂 Source: {result.sources_used.join(", ")}
                </span>
              )}
              <button className="export-btn" onClick={handleExportPDF}>
                ⬇ Export
              </button>

            </div>

            <AnswerPanel answer={result.answer} sourcesUsed={result.sources_used} />
            {result.citations && result.citations.length > 0 && (
              <div className="citations-section">
                <h3 className="citations-heading">
                  Source Documents ({result.citations.length})
                </h3>
                <div className="citations-grid">
                  {result.citations.map((citation, i) => (
                    <CitationCard key={i} citation={citation} index={i + 1} />
                  ))}
                </div>
              </div>
            )}

            {/* Analytics Chart Panel */}
          </section>
        )}
      </main>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-inner">
          <div className="footer-left">
            <p>Capstone Group 2 — Multi-Agent RAG / Investigative Intelligence</p>
            <div className="footer-team">
              {TEAM.map((name) => (
                <span key={name} className="team-name">{name}</span>
              ))}
            </div>
          </div>
          <div className="footer-right">
            <p>IRS 990 + FEC Filings</p>
            <p>Multi-Agent RAG System</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
/* Add these CSS classes to App.css */
